### ISSUE TITLE
로그인 버튼을 누르면 로그인 요청을 서버에 보낸다.

### ISSUE THREAD

**Issue by HongBoogie** [boostcampwm-2024/web25-funch#200]
### 🧑🏻‍💻 개발할 사항

- login 액션
- 관련한 msw 설정

<br><br>

### 🌈 인수 조건
- 로그인 버튼을 누르면 로그인 요청을 서버에 보낸다.

**Comment by WilleLee** [comment]
OAuth 도입으로 로그인 버튼 클릭 시 로그인 모달이 렌더링된다.

이후 각 버튼을 통해 OAuth 인증 프로세스가 시작된다.
