### ISSUE TITLE
회원 정보를 성공적으로 조회하면 정보를 상태로 저장하고 메인 페이지로 redirect한다.

### ISSUE THREAD

**Issue by HongBoogie** [boostcampwm-2024/web25-funch#201]
### 🧑🏻‍💻 개발할 사항

- use 컨텍스트 상태 세터

<br><br>

### 🌈 인수 조건

- 로그인 정보를 가진 Context에 저장한다.

**Comment by WilleLee** [comment]
OAuth 인증을 통해 받아온 정보를 유저 프로바이더에 저장한다.
