### ISSUE TITLE
StudioTextarea

### ISSUE THREAD

**Issue by HongBoogie** [boostcampwm-2024/web25-funch#226]
### 🧑🏻‍💻 개발할 사항

- textarea 래퍼 및 관련 컴포넌트
- textarea 입력 값 높이 변경에 따른 컴포넌트 형태 변환 기능

<br><br>

### 🌈 인수 조건

- StudioTextarea를 통해 방송 제목을 입력 가능

**Comment by WilleLee** [comment]
`StudioTextarea.tsx` 파일 내에 `handleChangeTextareaSize()` 메서드를 정의하여 `ref`로 전달한 `textarea`의 높이를 조절할 수 있도록 함.
