### ISSUE TITLE
버퍼링 최소화하기

### ISSUE THREAD

**Issue by HongBoogie** [boostcampwm-2024/web25-funch#323]
### 🧑🏻‍💻 개발할 사항

<br><br>

### 🌈 인수 조건
- 버퍼링을… 모아모아…

**Comment by WilleLee** [comment]
허용 레이턴시 길이를 늘려봤는데, 유의미한 차이는 나타나지 않았음.

```typescript
hlsRef.current = new Hls({
  lowLatencyMode: false,
  maxLiveSyncPlaybackRate: 1.5,
  liveSyncDuration: 4,
  liveMaxLatencyDuration: 8,
  liveDurationInfinity: true,
});
```

**Comment by WilleLee** [comment]
버퍼링 세터가 waiting 이벤트에 즉각적으로 나타나는 것이 아니라 2.5초의 타임아웃 이후 발동하도록 하였고, 중간에 playing 이벤트 발생 시 타임아웃이 클리어되도록 함. -> 버퍼링 UI 노출 최소화
