### ISSUE TITLE
MSW 환경 설정

### ISSUE THREAD

**Issue by HongBoogie** [boostcampwm-2024/web25-funch#53]
### 🧑🏻‍💻 개발할 사항

- msw 스타터 함수
- msw 이니셜라이저 컴포넌트

<br><br>

### 🌈 인수 조건
- handler, browser 설정을 통해 MSW를 사용 가능하게한다.
- Mock data를 추가하여 API Mocking이 가능하다.

**Comment by WilleLee** [comment]
서버 컴포넌트 확장 가능성 고려 필요
