### ISSUE TITLE
prettier 및 eslint 설정

### ISSUE THREAD

**Issue by HongBoogie** [boostcampwm-2024/web25-funch#54]
### 🧑🏻‍💻 개발할 사항

- eslint 설정 파일
- prettier 설정 파일
- 관련 플러그인 및 확장 라이브러리 설치 및 각 설정 파일에 적용 필요
- 필요 시 클라이언트와 루트 린트/프리티어 설정 분리

<br><br>

### 🌈 인수 조건
- prettier, eslint 설정을 완료한다.

**Comment by WilleLee** [comment]
eslint 설정에 필요한 라이브러리를 루트에 설치하기 위하여 루트에 npm init 하고 관련 모듈들을 설치하였다.

**Comment by WilleLee** [comment]
본래 서버 및 클라이언트에 대한 eslint/prettier 설정을 루트에서 모두 관리하고자 하였으나, next 프로젝트는 `next lint` 스크립트 명령어를 사용한다는 특이사항으로 인하여 프론트엔드의 eslint를 분리하게 되었다.

**Comment by WilleLee** [comment]
루트의 prettier 설정을 참고하도록 클라이언트의 eslint를 루트로 설정하지는 않았는데, 이게 좋은 방안인지 소통 필요.
